In [35]:
import torch

In [36]:
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [37]:
x.grad

In [38]:
y = 2 * torch.dot(x, x.T)
y

tensor(28., grad_fn=<MulBackward0>)

In [39]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [40]:
x.grad == 4 * x

tensor([True, True, True, True])

In [41]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [42]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [43]:
y.backward()

In [44]:
x.grad

tensor([1., 1., 1., 1.])

In [45]:
x.grad.zero_()
y = x * x

In [46]:
y

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)

In [47]:
y.sum()

tensor(14., grad_fn=<SumBackward0>)

In [48]:
y.sum().backward()

In [49]:
x.grad

tensor([0., 2., 4., 6.])

In [50]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [51]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x


In [52]:
u

tensor([0., 1., 4., 9.])

In [53]:
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [54]:
x.grad.zero_()
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

In [55]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c 

In [57]:
a = torch.randn(size=(), requires_grad=True)
a

tensor(0.7831, requires_grad=True)

In [58]:
d = f(a)
d

tensor(1603.8752, grad_fn=<MulBackward0>)

In [59]:
d.backward()

In [61]:
a.grad == d / a

tensor(True)